### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by blabno** [Real-Skill/scaffolding#4]
# Remove `develop` branch.
# Add readme to `master`
Add readme to `master` branch that would describe goal of this repo and list links to all the branches.
# We need some naming convention
* Do not add "scaffolding" word to branch name.
* Everything should be lowercased, words should be separated with dashes, i.e.:
 * angularjs
 * nodejs
 * expressjs
 * pure-javascript
 * javaee-postgress-arquillian

**Comment by aniaw** [comment]
I can't remove develop branch - set as default. I don't have permission to change it / delete it.

**Comment by blabno** [comment]
I've removed `develop` branch. Now `master` is default.

**Comment by blabno** [comment]
Link to mongo in readem is invalid.

**Comment by aniaw** [comment]
Link to mongo repaired.
